import type { Project } from '../project'

export const agencyPreset: Project = {
  id: 'project-agency',
  name: 'Fieldnote Studio',
  theme: {
    primaryColor: '#c8ff4d',
    secondaryColor: '#ffffff',
    backgroundColor: '#0b0b0d',
    surfaceColor: '#161618',
    textColor: '#f4f4f2',
    mutedColor: 'rgba(244, 244, 242, 0.6)',
    borderRadius: '10px',
    containerWidth: '1280px',
    fontFamily: '"Helvetica Neue", Arial, sans-serif',
    shadow: '0 30px 70px rgba(0, 0, 0, 0.45)',
  },
  assets: [],
  pages: [
    {
      id: 'page-home',
      name: 'Home',
      sections: [
        {
          id: 'section-agency-header',
          componentId: 'Header01',
          props: {
            logoText: 'Fieldnote',
            logoHref: '/',
            ctaText: 'Start a Project',
            ctaHref: '#contact',
          },
          variantId: 'minimal',
          style: {
            containerWidth: 1280,
            sticky: true,
            transparent: true,
            shadow: false,
            borderBottom: false,
          },
        },
        {
          id: 'section-agency-hero',
          componentId: 'Hero02',
          props: {
            eyebrow: 'Digital & creative studio',
            title: 'We design and build digital products for growing brands.',
            subtitle:
              'Fieldnote partners with founders and marketing teams to design, build, and launch websites and products that actually perform.',
            primaryCtaText: 'Start a Project',
            primaryCtaHref: '#contact',
            secondaryCtaText: 'See Our Services',
            secondaryCtaHref: '#services',
            heroImageAssetId: '',
            heroImageAlt: '',
          },
          variantId: 'image-first',
          style: {
            containerWidth: 1280,
            paddingTop: 96,
            paddingBottom: 96,
            imageRadius: 'large',
            imageRatio: 'landscape',
            contentAlignment: 'left',
            showImageBorder: false,
            contentSurface: false,
          },
        },
        {
          id: 'section-agency-logocloud',
          componentId: 'LogoCloud01',
          props: {
            eyebrow: 'Trusted by teams at',
            title: 'Companies we have helped build and grow',
            subtitle: 'A selection of the founders and marketing teams we have partnered with.',
            logo1AssetId: '',
            logo1CompanyName: 'Northwind Supply Co.',
            logo2AssetId: '',
            logo2CompanyName: 'Fieldstone Partners',
            logo3AssetId: '',
            logo3CompanyName: 'Harbor & Co.',
            logo4AssetId: '',
            logo4CompanyName: 'Lumen Analytics',
            logo5AssetId: '',
            logo5CompanyName: 'Greystone Capital',
            logo6AssetId: '',
            logo6CompanyName: 'Adler Studio',
          },
          variantId: 'centered-strip',
          style: {
            containerWidth: 1100,
            paddingTop: 56,
            paddingBottom: 56,
            logoTreatment: 'grayscale',
            showCaptions: true,
            logoSize: 'large',
          },
        },
        {
          id: 'section-agency-services',
          componentId: 'Services01',
          props: {
            eyebrow: 'What we do',
            title: 'Services built around your growth, not our org chart',
            subtitle: 'From the first strategy call to post-launch support, one team handles the whole thing.',
            service1Icon: 'compass',
            service1Title: 'Brand Strategy',
            service1Description:
              'We clarify who you are, who you are for, and why it matters before any design work begins.',
            service2Icon: 'layers',
            service2Title: 'Web Design',
            service2Description:
              'Considered, conversion-focused design for marketing sites, product sites, and everything in between.',
            service3Icon: 'tool',
            service3Title: 'Development',
            service3Description:
              'Fast, accessible, maintainable builds, with no framework lock-in and no unnecessary complexity.',
            service4Icon: 'chart',
            service4Title: 'Growth & Analytics',
            service4Description:
              'Ongoing iteration guided by real user behavior, not guesswork or vanity metrics.',
            service5Icon: 'shield',
            service5Title: 'Ongoing Support',
            service5Description:
              'A dedicated point of contact for updates, fixes, and small changes after launch.',
            service6Icon: 'spark',
            service6Title: 'Consulting',
            service6Description:
              'An outside perspective on product, brand, or technical decisions, billed by the hour.',
          },
          variantId: 'two-column',
          style: {
            containerWidth: 1200,
            paddingTop: 80,
            paddingBottom: 80,
            iconStyle: 'tinted',
            divider: true,
          },
        },
        {
          id: 'section-agency-stats',
          componentId: 'Stats01',
          props: {
            eyebrow: 'By the numbers',
            title: 'A decade of work you can actually verify',
            subtitle: 'The figures behind the studio, not just the pitch.',
            stat1Value: '10+',
            stat1Label: 'Years in business',
            stat1Description: 'Founded in 2014, still led by the same two partners.',
            stat2Value: '120+',
            stat2Label: 'Projects shipped',
            stat2Description: 'Across startups, agencies, and established brands.',
            stat3Value: '94%',
            stat3Label: 'Client retention',
            stat3Description: 'Most clients return for their next project or stay on retainer.',
            stat4Value: '< 48h',
            stat4Label: 'Average response time',
            stat4Description: 'A real person replies, not an autoresponder.',
          },
          variantId: 'featured',
          style: {
            containerWidth: 1100,
            paddingTop: 80,
            paddingBottom: 80,
            alignment: 'center',
            showDivider: true,
          },
        },
        {
          id: 'section-agency-features',
          componentId: 'Features01',
          props: {
            eyebrow: 'Why teams choose Fieldnote',
            title: 'A small team that moves like a big one',
            subtitle: 'No account managers relaying messages. You work directly with the people doing the work.',
            feature1Icon: 'bolt',
            feature1Title: 'Fast, without shortcuts',
            feature1Description:
              'Most engagements launch in 6 to 10 weeks, without cutting corners on quality.',
            feature2Icon: 'puzzle',
            feature2Title: 'Fits your existing stack',
            feature2Description:
              'We work with the tools and platforms you already use, not the ones we prefer.',
            feature3Icon: 'globe',
            feature3Title: 'Remote-first, always reachable',
            feature3Description:
              'Async by default, with a standing weekly call so nothing gets lost in translation.',
          },
          variantId: 'icon-left',
          style: {
            containerWidth: 1200,
            paddingTop: 80,
            paddingBottom: 80,
            iconStyle: 'outline',
            cardBorder: false,
          },
        },
        {
          id: 'section-agency-process',
          componentId: 'Process01',
          props: {
            eyebrow: 'How we work',
            title: 'A process built for clarity, not surprises',
            subtitle: 'Four steps, the same way every time, no matter the size of the project.',
            step1Number: '01',
            step1Title: 'Discovery',
            step1Description: 'We learn about your business, your goals, and what success actually looks like.',
            step2Number: '02',
            step2Title: 'Plan',
            step2Description: 'A clear scope, timeline, and budget agreed before any work begins.',
            step3Number: '03',
            step3Title: 'Build',
            step3Description: 'Steady progress with regular check-ins, so nothing arrives as a surprise.',
            step4Number: '04',
            step4Title: 'Launch & Support',
            step4Description: 'A final review, a proper handover, and support after you go live.',
          },
          variantId: 'editorial',
          style: {
            containerWidth: 1100,
            paddingTop: 80,
            paddingBottom: 80,
            showDivider: true,
            stepNumberStyle: 'badge',
            alignment: 'center',
          },
        },
        {
          id: 'section-agency-testimonials',
          componentId: 'Testimonials01',
          props: {
            eyebrow: 'What clients say',
            title: 'Feedback from people we have worked with',
            subtitle: 'A few words from founders and marketing leads we have partnered with recently.',
            testimonial1AvatarAssetId: '',
            testimonial1Name: 'Sara Whitfield',
            testimonial1Role: 'Head of Marketing',
            testimonial1Company: 'Northwind Supply Co.',
            testimonial1Text:
              'Fieldnote rebuilt our site in eight weeks and it converts noticeably better than the old one. They were direct about tradeoffs the whole way through.',
            testimonial2AvatarAssetId: '',
            testimonial2Name: 'Daniel Ortiz',
            testimonial2Role: 'Founder',
            testimonial2Company: 'Harbor & Co.',
            testimonial2Text:
              'We had worked with three agencies before this one. Fieldnote is the first that shipped on the date they promised.',
            testimonial3AvatarAssetId: '',
            testimonial3Name: 'Priya Nair',
            testimonial3Role: 'VP Product',
            testimonial3Company: 'Lumen Analytics',
            testimonial3Text:
              'Their team caught problems in our onboarding flow that we had missed for two years. Worth every invoice.',
          },
          variantId: 'stacked',
          style: {
            containerWidth: 800,
            paddingTop: 80,
            paddingBottom: 80,
            density: 'comfortable',
            avatarSize: 48,
            alignment: 'left',
            dividerStyle: 'line',
            showQuoteMark: true,
          },
        },
        {
          id: 'section-agency-faq',
          componentId: 'FAQ01',
          props: {
            eyebrow: 'Common questions',
            title: 'Answers before you ask',
            subtitle: 'The things most clients want to know before their first call.',
            faq1Question: 'How long does a typical project take?',
            faq1Answer:
              'Most website projects take 6 to 10 weeks from kickoff to launch, depending on scope. Larger product builds typically run 3 to 6 months.',
            faq2Question: 'How much does a project cost?',
            faq2Answer:
              'It depends on scope, but most engagements start around $15,000. We give you a fixed quote after a short discovery call, never an open-ended hourly estimate.',
            faq3Question: 'Do you work with early-stage startups?',
            faq3Answer:
              'Yes. About a third of our clients are pre-seed to Series A. We scope projects to match your stage and budget.',
            faq4Question: 'What happens after launch?',
            faq4Answer:
              'Every project includes 30 days of support after launch. After that, most clients move to a monthly retainer or pay for changes as needed.',
            faq5Question: 'Can you work with our existing team?',
            faq5Answer:
              'Often, yes. We regularly partner alongside in-house marketing and engineering teams rather than replacing them.',
            faq6Question: 'Do you sign contracts and NDAs?',
            faq6Answer:
              'Always. We sign your NDA before discovery and use a standard services agreement with clear scope and payment terms.',
          },
          variantId: 'split',
          style: {
            containerWidth: 880,
            paddingTop: 80,
            paddingBottom: 80,
            alignment: 'center',
            showDivider: true,
          },
        },
        {
          id: 'section-agency-cta',
          componentId: 'CTA01',
          props: {
            eyebrow: 'Ready when you are',
            title: 'Have a project in mind? Let’s talk.',
            subtitle: 'Book a 30-minute call and we will tell you honestly whether we are the right fit.',
            primaryLabel: 'Book a Call',
            primaryHref: '#contact',
            secondaryLabel: 'Email Us',
            secondaryHref: 'mailto:hello@fieldnote.studio',
          },
          variantId: 'boxed',
          style: {
            containerWidth: 960,
            paddingTop: 72,
            paddingBottom: 72,
            surface: false,
            alignment: 'center',
          },
        },
        {
          id: 'section-agency-contact',
          componentId: 'Contact01',
          props: {
            eyebrow: 'Get in touch',
            title: 'Tell us about your project',
            subtitle: 'We reply to every inquiry within two business days.',
            businessName: 'Fieldnote Studio',
            address: '118 Greene Street, Suite 4\nNew York, NY 10012',
            phone: '+1 (212) 555-0101',
            email: 'hello@fieldnote.studio',
            openingHours: 'Monday – Friday, 9:00 – 18:00 ET',
            ctaLabel: 'Start a Project',
            ctaHref: '#contact',
            directionsLabel: 'Get Directions',
            directionsUrl: 'https://maps.google.com/?q=118+Greene+Street+New+York+NY+10012',
          },
          variantId: 'information-card',
          style: {
            containerWidth: 1000,
            paddingTop: 80,
            paddingBottom: 80,
            alignment: 'center',
            surface: false,
            dividerStyle: 'line',
          },
        },
        {
          id: 'section-agency-footer',
          componentId: 'Footer01',
          props: {
            logoText: 'Fieldnote',
            description:
              'A digital and creative studio helping founders and marketing teams design, build, and ship products that perform.',
            email: 'hello@fieldnote.studio',
            phone: '+1 (212) 555-0101',
            copyrightText: '© 2026 Fieldnote Studio. All rights reserved.',
            backgroundColor: '#161618',
          },
          variantId: 'classic',
          style: {
            padding: 32,
            borderTop: true,
          },
        },
      ],
    },
  ],
}
