import type { Project } from '../project'

export const portfolioPreset: Project = {
  id: 'project-portfolio',
  name: 'Mara Vale — Portfolio',
  theme: {
    primaryColor: '#1f6f5c',
    secondaryColor: '#12110f',
    backgroundColor: '#fbfaf7',
    surfaceColor: '#ffffff',
    textColor: '#12110f',
    mutedColor: 'rgba(18, 17, 15, 0.55)',
    borderRadius: '4px',
    containerWidth: '960px',
    fontFamily: 'ui-serif, Georgia, Cambria, "Times New Roman", serif',
    shadow: '0 12px 30px rgba(18, 17, 15, 0.08)',
  },
  assets: [],
  pages: [
    {
      id: 'page-home',
      name: 'Home',
      sections: [
        {
          id: 'section-portfolio-header',
          componentId: 'Header01',
          props: {
            logoText: 'Mara Vale',
            logoHref: '/',
            ctaText: 'Work With Me',
            ctaHref: '#contact',
          },
          variantId: 'minimal',
          style: {
            containerWidth: 960,
            sticky: false,
            transparent: true,
            shadow: false,
            borderBottom: false,
          },
        },
        {
          id: 'section-portfolio-hero',
          componentId: 'Hero02',
          props: {
            eyebrow: 'Independent visual designer & art director',
            title: 'Considered design for brands, culture, and editorial work.',
            subtitle:
              'I partner with small brands, cultural projects, and editorial teams to shape identity, art direction, and the details most studios skip.',
            primaryCtaText: 'View Selected Work',
            primaryCtaHref: '#work',
            secondaryCtaText: 'Work With Me',
            secondaryCtaHref: '#contact',
            heroImageAssetId: '',
            heroImageAlt: '',
          },
          variantId: 'image-first',
          style: {
            containerWidth: 960,
            paddingTop: 72,
            paddingBottom: 64,
            imageRadius: 'small',
            imageRatio: 'portrait',
            contentAlignment: 'left',
            showImageBorder: true,
            contentSurface: false,
          },
        },
        {
          id: 'section-portfolio-gallery',
          componentId: 'Gallery01',
          props: {
            eyebrow: 'Selected Work',
            title: 'A few projects I can talk about',
            subtitle: 'Brand identity, campaign direction, and editorial design for clients across culture and retail.',
            image1AssetId: '',
            image1Alt: 'Brand identity system for a cultural festival, shown across print and signage',
            image2AssetId: '',
            image2Alt: 'Editorial spread from a magazine art direction project',
            image3AssetId: '',
            image3Alt: 'Packaging design for an independent skincare brand',
            image4AssetId: '',
            image4Alt: 'Campaign photography direction for a seasonal retail launch',
            image5AssetId: '',
            image5Alt: 'Website homepage design for a nonprofit arts organization',
            image6AssetId: '',
            image6Alt: 'Typeface and logotype exploration for a boutique hotel',
          },
          variantId: 'featured',
          style: {
            containerWidth: 960,
            paddingTop: 72,
            paddingBottom: 64,
            imageRadius: 4,
            imageGap: 16,
            imageRatio: 'portrait',
            showBorder: true,
          },
        },
        {
          id: 'section-portfolio-services',
          componentId: 'Services01',
          props: {
            eyebrow: 'How I Can Help',
            title: 'A few ways we might work together',
            subtitle: 'Most projects fall into one of these, though the best work usually blends a few.',
            service1Icon: 'layers',
            service1Title: 'Brand Identity',
            service1Description:
              'Logo, typography, color, and the guidelines to keep it consistent as your team grows.',
            service2Icon: 'camera',
            service2Title: 'Campaign Art Direction',
            service2Description:
              'Creative direction for photography, video, and seasonal campaigns, from concept to final asset.',
            service3Icon: 'compass',
            service3Title: 'Editorial Design',
            service3Description:
              'Art direction and layout for print and digital editorial, from single features to full issues.',
            service4Icon: 'tool',
            service4Title: 'Website Direction',
            service4Description:
              'Design direction for a new or refreshed website, working alongside your developer or agency.',
            service5Icon: 'spark',
            service5Title: 'Launch Support',
            service5Description:
              'Hands-on support through a launch week, keeping design consistent across every touchpoint.',
            service6Icon: 'shield',
            service6Title: 'Creative Consulting',
            service6Description:
              'An outside perspective on brand or creative decisions, billed by the day or the project.',
          },
          variantId: 'two-column',
          style: {
            containerWidth: 900,
            paddingTop: 72,
            paddingBottom: 64,
            iconStyle: 'none',
            divider: true,
          },
        },
        {
          id: 'section-portfolio-features',
          componentId: 'Features01',
          props: {
            eyebrow: 'How I Work',
            title: 'A few principles that shape every project',
            subtitle: 'Not a manifesto, just the things I keep coming back to.',
            feature1Icon: 'sparkles',
            feature1Title: 'Concept before decoration',
            feature1Description:
              'Every project starts with a clear idea. The visual language comes after, not instead of one.',
            feature2Icon: 'puzzle',
            feature2Title: 'Details are not optional',
            feature2Description:
              'Type, spacing, and material choices get the same attention as the big idea, right up to delivery.',
            feature3Icon: 'globe',
            feature3Title: 'Work that travels',
            feature3Description:
              'Every system is designed to hold up across print, screen, and whatever comes next.',
          },
          variantId: 'grid',
          style: {
            containerWidth: 900,
            paddingTop: 72,
            paddingBottom: 64,
            iconStyle: 'solid',
            cardBorder: false,
          },
        },
        {
          id: 'section-portfolio-process',
          componentId: 'Process01',
          props: {
            eyebrow: 'How We Would Work Together',
            title: 'A simple process, the same for every project',
            subtitle: 'Four steps, whether it is a two-week identity sprint or a six-month editorial partnership.',
            step1Number: '01',
            step1Title: 'Conversation',
            step1Description:
              'A short call to understand the project, the timeline, and whether I am the right fit.',
            step2Number: '02',
            step2Title: 'Proposal',
            step2Description:
              'A clear scope, timeline, and cost, usually within a few days of our first conversation.',
            step3Number: '03',
            step3Title: 'Design',
            step3Description:
              'Concept, refinement, and regular check-ins, with room for real feedback at every stage.',
            step4Number: '04',
            step4Title: 'Handoff',
            step4Description: 'Final files, guidelines, and a walkthrough, so your team can carry the work forward.',
          },
          variantId: 'horizontal',
          style: {
            containerWidth: 1000,
            paddingTop: 72,
            paddingBottom: 64,
            showDivider: true,
            stepNumberStyle: 'plain',
            alignment: 'center',
          },
        },
        {
          id: 'section-portfolio-testimonials',
          componentId: 'Testimonials01',
          props: {
            eyebrow: 'Client Feedback',
            title: 'What collaborators say',
            subtitle: 'A few notes from people I have worked with recently.',
            testimonial1AvatarAssetId: '',
            testimonial1Name: 'Isabel Duarte',
            testimonial1Role: 'Founder',
            testimonial1Company: 'Casa Estúdio',
            testimonial1Text:
              'Mara understood the brand better after one conversation than our last agency did after three months. The identity still holds up two years later.',
            testimonial2AvatarAssetId: '',
            testimonial2Name: 'Julian Ferreira',
            testimonial2Role: 'Editor-in-Chief',
            testimonial2Company: 'Ambit Magazine',
            testimonial2Text:
              'She art-directed four issues for us and never once missed a deadline or a detail. Rare combination.',
            testimonial3AvatarAssetId: '',
            testimonial3Name: 'Noor Al-Sayed',
            testimonial3Role: 'Program Director',
            testimonial3Company: 'Meridian Arts Council',
            testimonial3Text:
              'We needed someone who could work with a small budget and a big ambition. Mara delivered both.',
          },
          variantId: 'stacked',
          style: {
            containerWidth: 760,
            paddingTop: 72,
            paddingBottom: 64,
            density: 'compact',
            avatarSize: 40,
            alignment: 'left',
            dividerStyle: 'line',
            showQuoteMark: false,
          },
        },
        {
          id: 'section-portfolio-faq',
          componentId: 'FAQ01',
          props: {
            eyebrow: 'Before We Start',
            title: 'A few things people usually ask',
            subtitle: 'If your question is not here, it is probably faster to just ask directly.',
            faq1Question: 'Are you currently available for new projects?',
            faq1Answer:
              'I take on a limited number of projects at a time. Check the note in the contact section below, or ask directly and I will give you an honest answer.',
            faq2Question: 'How long do projects typically take?',
            faq2Answer:
              'A brand identity usually runs four to six weeks. Editorial and campaign work varies more, depending on scope and how many rounds of feedback we need.',
            faq3Question: 'Do you take on ongoing or retainer work?',
            faq3Answer:
              'Yes, for a small number of clients. Retainers usually start after we have completed at least one project together.',
            faq4Question: 'Do you work with clients remotely?',
            faq4Answer:
              'Yes. Most of my clients are remote, and I run projects over video calls, shared files, and async feedback.',
            faq5Question: 'Who owns the final files and usage rights?',
            faq5Answer:
              'Once a project is paid in full, you own the final deliverables and agreed usage rights. Working files and unused concepts remain mine unless we agree otherwise.',
            faq6Question: 'What is a realistic starting budget?',
            faq6Answer:
              'Most brand identity projects start around $6,000. Editorial and campaign work is scoped individually based on deliverables.',
          },
          variantId: 'minimal-list',
          style: {
            containerWidth: 760,
            paddingTop: 72,
            paddingBottom: 64,
            alignment: 'left',
            showDivider: true,
          },
        },
        {
          id: 'section-portfolio-cta',
          componentId: 'CTA01',
          props: {
            eyebrow: 'Have a Project in Mind?',
            title: 'Let’s talk about it.',
            subtitle: 'Tell me a little about the project and the timeline, and I will reply within a couple of days.',
            primaryLabel: 'Start an Inquiry',
            primaryHref: '#contact',
            secondaryLabel: 'Email Directly',
            secondaryHref: 'mailto:hello@maravale.studio',
          },
          variantId: 'centered',
          style: {
            containerWidth: 820,
            paddingTop: 64,
            paddingBottom: 56,
            surface: false,
            alignment: 'center',
          },
        },
        {
          id: 'section-portfolio-form',
          componentId: 'Form01',
          props: {
            eyebrow: 'Work With Me',
            title: 'Say hello',
            subtitle: 'Currently booking new projects for Q2 2026. The fastest way to reach me is by email.',
            formTitle: 'Project inquiry',
            formDescription: 'Share a little about the project and the timeline, and I will reply within a couple of days.',
            nameLabel: 'Your name',
            emailLabel: 'Email address',
            phoneLabel: 'Phone number',
            messageLabel: 'Tell me about your project',
            submitLabel: 'Send Inquiry',
            formAction: '',
            helperNote: 'I typically reply within a couple of days.',
            sideTitle: 'Prefer to reach out directly?',
            sideDescription: 'Currently booking new projects for Q2 2026.',
            email: 'hello@maravale.studio',
            phone: '+351 91 555 0123',
            address: 'Lisbon, Portugal\n(Studio visits by appointment)',
            openingHours: 'Monday – Friday, by appointment',
          },
          variantId: 'split',
          style: {
            containerWidth: 820,
            paddingTop: 72,
            paddingBottom: 64,
            alignment: 'center',
            surface: false,
            fieldStyle: 'outline',
            showSidePanel: true,
          },
        },
        {
          id: 'section-portfolio-footer',
          componentId: 'Footer01',
          props: {
            logoText: 'Mara Vale',
            description: 'Independent visual designer and art director based in Lisbon, working with clients worldwide.',
            email: 'hello@maravale.studio',
            phone: '+351 91 555 0123',
            copyrightText: '© 2026 Mara Vale. All rights reserved.',
            backgroundColor: '#ffffff',
          },
          variantId: 'minimal',
          style: {
            padding: 28,
            borderTop: false,
          },
        },
      ],
    },
  ],
}
