import type { Project } from '../project'

export const restaurantPreset: Project = {
  id: 'project-restaurant',
  name: 'Luma Bistro',
  theme: {
    primaryColor: '#b4491f',
    secondaryColor: '#231710',
    backgroundColor: '#faf3ea',
    surfaceColor: '#ffffff',
    textColor: '#231710',
    mutedColor: 'rgba(35, 23, 16, 0.55)',
    borderRadius: '18px',
    containerWidth: '1140px',
    fontFamily: 'Georgia, "Times New Roman", serif',
    shadow: '0 18px 50px rgba(35, 23, 16, 0.12)',
  },
  assets: [],
  pages: [
    {
      id: 'page-home',
      name: 'Home',
      sections: [
        {
          id: 'section-restaurant-header',
          componentId: 'Header01',
          props: {
            logoText: 'Luma Bistro',
            logoHref: '/',
            ctaText: 'Reserve a Table',
            ctaHref: '#reserve',
          },
          variantId: 'centered',
          style: {
            containerWidth: 1100,
            sticky: true,
            transparent: false,
            shadow: true,
            borderBottom: true,
          },
        },
        {
          id: 'section-restaurant-hero',
          componentId: 'Hero02',
          props: {
            eyebrow: 'Seasonal neighborhood dining',
            title: 'A seasonal menu, cooked over an open flame.',
            subtitle:
              'Luma Bistro is a neighborhood restaurant serving modern, ingredient-led plates from local producers, paired with a thoughtfully chosen wine list.',
            primaryCtaText: 'Reserve a Table',
            primaryCtaHref: '#reserve',
            secondaryCtaText: 'View Our Menu Highlights',
            secondaryCtaHref: '#menu',
            heroImageAssetId: '',
            heroImageAlt: '',
          },
          variantId: 'image-first',
          style: {
            containerWidth: 1100,
            paddingTop: 64,
            paddingBottom: 64,
            imageRadius: 'large',
            imageRatio: 'landscape',
            contentAlignment: 'left',
            showImageBorder: false,
            contentSurface: false,
          },
        },
        {
          id: 'section-restaurant-services',
          componentId: 'Services01',
          props: {
            eyebrow: 'The Menu',
            title: 'A concise menu, built around the season',
            subtitle: 'Everything on our table reflects what local producers bring us that week.',
            service1Icon: 'leaf',
            service1Title: 'Seasonal Dinner',
            service1Description:
              'A rotating dinner menu built around what is fresh that week, served nightly Tuesday through Sunday.',
            service2Icon: 'compass',
            service2Title: 'Weekend Lunch',
            service2Description:
              'A shorter, lighter menu served Saturday and Sunday from noon, ideal for a slower afternoon.',
            service3Icon: 'layers',
            service3Title: 'Private Dining',
            service3Description:
              'Our back room seats up to fourteen for celebrations, work dinners, and family gatherings.',
            service4Icon: 'chart',
            service4Title: 'Wine List',
            service4Description:
              'A compact, well-chosen list weighted toward small growers, with new additions every season.',
            service5Icon: 'shield',
            service5Title: 'Vegetarian & Dietary Options',
            service5Description:
              'A full vegetarian tasting menu is available nightly, and most dishes can be adapted on request.',
            service6Icon: 'spark',
            service6Title: 'Chef’s Tasting Menu',
            service6Description:
              'A five-course seasonal tasting menu, available for the whole table by request.',
          },
          variantId: 'list',
          style: {
            containerWidth: 1100,
            paddingTop: 72,
            paddingBottom: 72,
            iconStyle: 'tinted',
            divider: true,
          },
        },
        {
          id: 'section-restaurant-gallery',
          componentId: 'Gallery01',
          props: {
            eyebrow: 'A Closer Look',
            title: 'The room, the table, the plates',
            subtitle: 'A few glimpses of what to expect when you visit.',
            image1AssetId: '',
            image1Alt: 'Close-up of a seasonal plated dish on the pass',
            image2AssetId: '',
            image2Alt: 'The dining room set for evening service',
            image3AssetId: '',
            image3Alt: 'A glass of natural wine on a linen tablecloth',
            image4AssetId: '',
            image4Alt: 'Fresh produce laid out before evening prep',
            image5AssetId: '',
            image5Alt: 'The bar and open kitchen from the dining room',
            image6AssetId: '',
            image6Alt: 'A table set for two near the front window',
          },
          variantId: 'editorial',
          style: {
            containerWidth: 1140,
            paddingTop: 72,
            paddingBottom: 72,
            imageRadius: 16,
            imageGap: 16,
            imageRatio: 'landscape',
            showBorder: false,
          },
        },
        {
          id: 'section-restaurant-stats',
          componentId: 'Stats01',
          props: {
            eyebrow: 'Since we opened',
            title: 'A neighborhood spot people keep coming back to',
            subtitle: 'The numbers behind the kitchen, not just the reviews.',
            stat1Value: '8+',
            stat1Label: 'Years open',
            stat1Description: 'Family-run since 2018, in the same room the whole time.',
            stat2Value: '40+',
            stat2Label: 'Seasonal dishes a year',
            stat2Description: 'The menu changes with what is actually in season, not on a fixed schedule.',
            stat3Value: '12',
            stat3Label: 'Local producers',
            stat3Description: 'Farms, fishers, and growers within a few hours of the kitchen.',
            stat4Value: '4.8',
            stat4Label: 'Average guest rating',
            stat4Description: 'Based on reviews across our most-used booking platforms.',
          },
          variantId: 'two-by-two',
          style: {
            containerWidth: 1000,
            paddingTop: 72,
            paddingBottom: 72,
            alignment: 'center',
            showDivider: true,
          },
        },
        {
          id: 'section-restaurant-features',
          componentId: 'Features01',
          props: {
            eyebrow: 'Why guests choose Luma',
            title: 'Small room, big attention to detail',
            subtitle: 'What keeps our regulars coming back, in their own words as much as ours.',
            feature1Icon: 'sparkles',
            feature1Title: 'A menu that actually changes',
            feature1Description:
              'We rebuild the menu around what is in season, so a visit in March looks different from one in September.',
            feature2Icon: 'layers',
            feature2Title: 'An intimate room',
            feature2Description:
              'Twenty-eight seats means every table gets real attention from the kitchen and the floor.',
            feature3Icon: 'globe',
            feature3Title: 'Wine, chosen thoughtfully',
            feature3Description:
              'Our list favors small, low-intervention producers, with pairings suggested for every course on request.',
          },
          variantId: 'icon-left',
          style: {
            containerWidth: 1100,
            paddingTop: 72,
            paddingBottom: 72,
            iconStyle: 'outline',
            cardBorder: false,
          },
        },
        {
          id: 'section-restaurant-testimonials',
          componentId: 'Testimonials01',
          props: {
            eyebrow: 'From our guests',
            title: 'What people say after dinner',
            subtitle: 'A few notes from recent visits, shared with permission.',
            testimonial1AvatarAssetId: '',
            testimonial1Name: 'Emily Carter',
            testimonial1Role: 'Regular guest',
            testimonial1Company: '',
            testimonial1Text:
              'We have been coming for years and the tasting menu still surprises us. Never showy, always precise.',
            testimonial2AvatarAssetId: '',
            testimonial2Name: 'Marcus Webb',
            testimonial2Role: 'First-time visitor',
            testimonial2Company: '',
            testimonial2Text:
              'Booked on a whim for a Tuesday dinner and it was one of the best meals we have had this year. Small room, big flavor.',
            testimonial3AvatarAssetId: '',
            testimonial3Name: 'Priya Shah',
            testimonial3Role: 'Hosted a private dinner',
            testimonial3Company: '',
            testimonial3Text:
              'We used the back room for a birthday of twelve. The staff handled everything without making it feel like an event.',
          },
          variantId: 'featured',
          style: {
            containerWidth: 900,
            paddingTop: 72,
            paddingBottom: 72,
            density: 'comfortable',
            avatarSize: 48,
            alignment: 'center',
            dividerStyle: 'line',
            showQuoteMark: true,
          },
        },
        {
          id: 'section-restaurant-faq',
          componentId: 'FAQ01',
          props: {
            eyebrow: 'Before you book',
            title: 'Good to know',
            subtitle: 'The questions we hear most often when guests call to reserve.',
            faq1Question: 'How far in advance should we book?',
            faq1Answer:
              'For weekend dinners we recommend booking one to two weeks ahead. Weekday and weekend lunch tables are usually easier to find on shorter notice.',
            faq2Question: 'Can you accommodate dietary restrictions?',
            faq2Answer:
              'Yes. Let us know when you book and we will happily adjust dishes for allergies, vegetarian, or other dietary needs.',
            faq3Question: 'Do you host private events?',
            faq3Answer:
              'Our back room seats up to fourteen and can be booked for private dinners, celebrations, or work events. Contact us directly to check availability.',
            faq4Question: 'Are children welcome?',
            faq4Answer:
              'Yes, children are welcome at lunch and early dinner seatings. We do not have a dedicated children’s menu, but happily adjust portions.',
            faq5Question: 'What is your cancellation policy?',
            faq5Answer:
              'We ask for at least 24 hours notice to cancel or change a reservation. Same-day cancellations may be subject to a small fee for parties of six or more.',
            faq6Question: 'Is there parking nearby?',
            faq6Answer:
              'Street parking is available on the surrounding blocks, and a public lot sits two minutes’ walk from the front door.',
          },
          variantId: 'minimal-list',
          style: {
            containerWidth: 820,
            paddingTop: 72,
            paddingBottom: 72,
            alignment: 'center',
            showDivider: true,
          },
        },
        {
          id: 'section-restaurant-cta',
          componentId: 'CTA01',
          props: {
            eyebrow: 'Ready to visit',
            title: 'Reserve your table at Luma Bistro',
            subtitle: 'Tables are limited, especially on weekends. Book ahead to make sure we have a spot for you.',
            primaryLabel: 'Reserve a Table',
            primaryHref: '#reserve',
            secondaryLabel: 'Call the Restaurant',
            secondaryHref: 'tel:+15035550148',
          },
          variantId: 'split',
          style: {
            containerWidth: 960,
            paddingTop: 64,
            paddingBottom: 64,
            surface: false,
            alignment: 'center',
          },
        },
        {
          id: 'section-restaurant-contact',
          componentId: 'Contact01',
          props: {
            eyebrow: 'Visit Us',
            title: 'Find us on the corner',
            subtitle: 'We look forward to having you at the table.',
            businessName: 'Luma Bistro',
            address: '482 Alder Street\nPortland, OR 97214',
            phone: '+1 (503) 555-0148',
            email: 'hello@lumabistro.com',
            openingHours: 'Dinner: Tuesday – Sunday, 5:00 – 22:00\nWeekend Lunch: Saturday – Sunday, 12:00 – 14:30',
            ctaLabel: 'Reserve a Table',
            ctaHref: '#reserve',
            directionsLabel: 'Get Directions',
            directionsUrl: 'https://maps.google.com/?q=482+Alder+Street+Portland+OR+97214',
          },
          variantId: 'split',
          style: {
            containerWidth: 1000,
            paddingTop: 72,
            paddingBottom: 72,
            alignment: 'center',
            surface: false,
            dividerStyle: 'line',
          },
        },
        {
          id: 'section-restaurant-footer',
          componentId: 'Footer01',
          props: {
            logoText: 'Luma Bistro',
            description: 'A seasonal neighborhood restaurant serving modern, ingredient-led plates from local producers.',
            email: 'hello@lumabistro.com',
            phone: '+1 (503) 555-0148',
            copyrightText: '© 2026 Luma Bistro. All rights reserved.',
            backgroundColor: '#ffffff',
          },
          variantId: 'minimal',
          style: {
            padding: 32,
            borderTop: true,
          },
        },
      ],
    },
  ],
}
