import type { Project } from '../project'

export const saasPreset: Project = {
  id: 'project-saas',
  name: 'Northstar',
  theme: {
    primaryColor: '#5b5bf5',
    secondaryColor: '#151233',
    backgroundColor: '#f6f6fd',
    surfaceColor: '#ffffff',
    textColor: '#151233',
    mutedColor: 'rgba(21, 18, 51, 0.55)',
    borderRadius: '20px',
    containerWidth: '1200px',
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    shadow: '0 24px 60px rgba(21, 18, 51, 0.1)',
  },
  assets: [],
  pages: [
    {
      id: 'page-home',
      name: 'Home',
      sections: [
        {
          id: 'section-saas-header',
          componentId: 'Header01',
          props: {
            logoText: 'Northstar',
            logoHref: '/',
            ctaText: 'Book a Demo',
            ctaHref: '#demo',
          },
          variantId: 'classic',
          style: {
            containerWidth: 1200,
            sticky: true,
            transparent: false,
            shadow: true,
            borderBottom: true,
          },
        },
        {
          id: 'section-saas-hero',
          componentId: 'Hero02',
          props: {
            eyebrow: 'Workflow & reporting platform',
            title: 'One clear view of how your team is actually operating.',
            subtitle:
              'Northstar pulls your workflows, tickets, and reporting into a single live dashboard, so operations and customer success teams stop reconciling spreadsheets by hand.',
            primaryCtaText: 'Book a Demo',
            primaryCtaHref: '#demo',
            secondaryCtaText: 'Start Free',
            secondaryCtaHref: '#contact',
            heroImageAssetId: '',
            heroImageAlt: '',
          },
          variantId: 'split-image',
          style: {
            containerWidth: 1200,
            paddingTop: 80,
            paddingBottom: 80,
            imageRadius: 'large',
            imageRatio: 'landscape',
            contentAlignment: 'left',
            showImageBorder: false,
            contentSurface: false,
          },
        },
        {
          id: 'section-saas-logocloud',
          componentId: 'LogoCloud01',
          props: {
            eyebrow: 'Trusted by operations teams at',
            title: 'Teams who run on Northstar',
            subtitle: 'From early-stage startups to scaling operations teams.',
            logo1AssetId: '',
            logo1CompanyName: 'Brightline',
            logo2AssetId: '',
            logo2CompanyName: 'Fernwood Analytics',
            logo3AssetId: '',
            logo3CompanyName: 'Kestrel Ops',
            logo4AssetId: '',
            logo4CompanyName: 'Vantage Point',
            logo5AssetId: '',
            logo5CompanyName: 'Meridian Labs',
            logo6AssetId: '',
            logo6CompanyName: 'Anchorpoint',
          },
          variantId: 'grid',
          style: {
            containerWidth: 1100,
            paddingTop: 56,
            paddingBottom: 56,
            logoTreatment: 'grayscale',
            showCaptions: true,
            logoSize: 'small',
          },
        },
        {
          id: 'section-saas-features',
          componentId: 'Features01',
          props: {
            eyebrow: 'What Northstar does',
            title: 'Everything your operations team checks every morning, in one place',
            subtitle: 'No more stitching together spreadsheets, tickets, and status updates before a Monday standup.',
            feature1Icon: 'chart',
            feature1Title: 'Live Dashboards',
            feature1Description:
              'Real-time visibility into workflow status, ticket volume, and team capacity, updated as work happens.',
            feature2Icon: 'bolt',
            feature2Title: 'Workflow Automation',
            feature2Description:
              'Automate routing, approvals, and escalations so nothing sits waiting for someone to notice it.',
            feature3Icon: 'layers',
            feature3Title: 'Team Visibility',
            feature3Description:
              'See who owns what, what is overdue, and where work is actually stuck, without asking in a channel.',
          },
          variantId: 'minimal',
          style: {
            containerWidth: 1100,
            paddingTop: 80,
            paddingBottom: 80,
            iconStyle: 'tinted',
            cardBorder: true,
          },
        },
        {
          id: 'section-saas-stats',
          componentId: 'Stats01',
          props: {
            eyebrow: 'Why teams switch',
            title: 'The numbers operations leads actually care about',
            subtitle: 'Not vanity metrics. The things that change how a team spends its week.',
            stat1Value: '6+',
            stat1Label: 'Hours saved per week',
            stat1Description: 'The average time an operations lead gets back once manual status updates stop.',
            stat2Value: '3x',
            stat2Label: 'Faster reporting',
            stat2Description: 'Weekly reporting that used to take an afternoon now takes about twenty minutes.',
            stat3Value: '400+',
            stat3Label: 'Active teams',
            stat3Description: 'From five-person startups to 200-person operations organizations.',
            stat4Value: '99.9%',
            stat4Label: 'Uptime',
            stat4Description: 'Measured over the trailing twelve months, published on our status page.',
          },
          variantId: 'four-column',
          style: {
            containerWidth: 1100,
            paddingTop: 80,
            paddingBottom: 80,
            alignment: 'center',
            showDivider: true,
          },
        },
        {
          id: 'section-saas-services',
          componentId: 'Services01',
          props: {
            eyebrow: 'Built for how ops teams actually work',
            title: 'One platform, four teams, one shared view',
            subtitle: 'Northstar adapts to how each team already works, without forcing a new process on day one.',
            service1Icon: 'compass',
            service1Title: 'Operations Teams',
            service1Description:
              'Track process health across every workflow, with alerts when something falls outside normal range.',
            service2Icon: 'chart',
            service2Title: 'Customer Success',
            service2Description:
              'See account health, open tickets, and renewal risk in one view instead of three tools.',
            service3Icon: 'layers',
            service3Title: 'Founders & Leadership',
            service3Description:
              'A weekly rollup of what shipped, what slipped, and what needs a decision, without chasing updates.',
            service4Icon: 'tool',
            service4Title: 'Internal Tools Teams',
            service4Description:
              'Connect to the systems you already use through our API and prebuilt integrations.',
            service5Icon: 'shield',
            service5Title: 'Data & Reporting',
            service5Description:
              'Every workflow event is logged and exportable, so reporting is never a manual reconstruction.',
            service6Icon: 'spark',
            service6Title: 'Automation Builder',
            service6Description:
              'Set up rules for routing, reminders, and escalations without writing code.',
          },
          variantId: 'grid',
          style: {
            containerWidth: 1200,
            paddingTop: 80,
            paddingBottom: 80,
            iconStyle: 'tinted',
            divider: true,
          },
        },
        {
          id: 'section-saas-process',
          componentId: 'Process01',
          props: {
            eyebrow: 'Getting started',
            title: 'Most teams are fully onboarded within two weeks',
            subtitle: 'A guided setup, not a self-serve maze.',
            step1Number: '01',
            step1Title: 'Connect your tools',
            step1Description:
              'Link your existing ticketing, spreadsheet, or workflow tools through our guided integration setup.',
            step2Number: '02',
            step2Title: 'Map your workflows',
            step2Description:
              'We help you translate your current process into Northstar boards and automation rules.',
            step3Number: '03',
            step3Title: 'Invite your team',
            step3Description:
              'Roll out to your team with role-based views, so everyone sees only what is relevant to them.',
            step4Number: '04',
            step4Title: 'Go live with reporting',
            step4Description:
              'Turn on live dashboards and weekly reporting once your team is comfortable with the workflow.',
          },
          variantId: 'vertical',
          style: {
            containerWidth: 1000,
            paddingTop: 80,
            paddingBottom: 80,
            showDivider: true,
            stepNumberStyle: 'outline',
            alignment: 'left',
          },
        },
        {
          id: 'section-saas-testimonials',
          componentId: 'Testimonials01',
          props: {
            eyebrow: 'What customers say',
            title: 'Feedback from operations and CS leads',
            subtitle: 'A few notes from teams running on Northstar today.',
            testimonial1AvatarAssetId: '',
            testimonial1Name: 'Rachel Kim',
            testimonial1Role: 'Head of Operations',
            testimonial1Company: 'Brightline',
            testimonial1Text:
              'We replaced four spreadsheets and a shared inbox with one Northstar board. Our weekly ops review is now fifteen minutes instead of an hour.',
            testimonial2AvatarAssetId: '',
            testimonial2Name: 'Tomás Alvarez',
            testimonial2Role: 'VP Customer Success',
            testimonial2Company: 'Fernwood Analytics',
            testimonial2Text:
              'Account health used to live in someone’s head. Now the whole team can see it, and renewals stopped being a surprise.',
            testimonial3AvatarAssetId: '',
            testimonial3Name: 'Grace Whitfield',
            testimonial3Role: 'Founder',
            testimonial3Company: 'Kestrel Ops',
            testimonial3Text:
              'Northstar was the first tool our ops and support teams both actually adopted without a mandate from me.',
          },
          variantId: 'row',
          style: {
            containerWidth: 1100,
            paddingTop: 80,
            paddingBottom: 80,
            density: 'comfortable',
            avatarSize: 48,
            alignment: 'left',
            dividerStyle: 'line',
            showQuoteMark: true,
          },
        },
        {
          id: 'section-saas-faq',
          componentId: 'FAQ01',
          props: {
            eyebrow: 'Questions',
            title: 'Answers before you book a demo',
            subtitle: 'The things most teams ask before switching tools.',
            faq1Question: 'How much does Northstar cost?',
            faq1Answer:
              'Pricing is based on team size, starting at $49 per user per month on our Team plan. Annual billing includes a discount, and we offer custom pricing for larger operations teams.',
            faq2Question: 'Is there a free trial?',
            faq2Answer:
              'Yes. Every plan includes a 14-day free trial with full access, no credit card required to start.',
            faq3Question: 'What integrations do you support?',
            faq3Answer:
              'Northstar connects with most common ticketing, spreadsheet, and communication tools out of the box, plus a REST API for anything custom.',
            faq4Question: 'How long does onboarding take?',
            faq4Answer: 'Most teams are fully set up within two weeks, including workflow mapping and team training.',
            faq5Question: 'How do you handle data security?',
            faq5Answer:
              'All data is encrypted in transit and at rest. We are SOC 2 Type II compliant and undergo annual third-party security audits.',
            faq6Question: 'Can we cancel anytime?',
            faq6Answer:
              'Yes. Monthly plans can be cancelled anytime from your account settings. Annual plans can be cancelled at renewal.',
          },
          variantId: 'centered',
          style: {
            containerWidth: 880,
            paddingTop: 80,
            paddingBottom: 80,
            alignment: 'center',
            showDivider: true,
          },
        },
        {
          id: 'section-saas-cta',
          componentId: 'CTA01',
          props: {
            eyebrow: 'See it in action',
            title: 'Book a 20-minute demo with our team',
            subtitle: 'We will walk through your current workflow and show you exactly how Northstar would map to it.',
            primaryLabel: 'Book a Demo',
            primaryHref: '#demo',
            secondaryLabel: 'Start Free Trial',
            secondaryHref: '#contact',
          },
          variantId: 'centered',
          style: {
            containerWidth: 960,
            paddingTop: 64,
            paddingBottom: 64,
            surface: true,
            alignment: 'center',
          },
        },
        {
          id: 'section-saas-contact',
          componentId: 'Contact01',
          props: {
            eyebrow: 'Talk to sales',
            title: 'Get in touch with our team',
            subtitle: 'We typically reply within one business day.',
            businessName: 'Northstar, Inc.',
            address: '95 Third Street, Suite 700\nSan Francisco, CA 94103',
            phone: '+1 (650) 555-0119',
            email: 'sales@northstar.io',
            openingHours: 'Monday – Friday, 9:00 – 18:00 PT',
            ctaLabel: 'Book a Demo',
            ctaHref: '#demo',
            directionsLabel: 'Get Directions',
            directionsUrl: 'https://maps.google.com/?q=95+Third+Street+San+Francisco+CA+94103',
          },
          variantId: 'centered',
          style: {
            containerWidth: 1000,
            paddingTop: 80,
            paddingBottom: 80,
            alignment: 'center',
            surface: false,
            dividerStyle: 'line',
          },
        },
        {
          id: 'section-saas-footer',
          componentId: 'Footer01',
          props: {
            logoText: 'Northstar',
            description: 'The workflow and reporting platform for growing operations teams.',
            email: 'support@northstar.io',
            phone: '+1 (650) 555-0119',
            copyrightText: '© 2026 Northstar, Inc. All rights reserved.',
            backgroundColor: '#ffffff',
          },
          variantId: 'minimal',
          style: {
            padding: 32,
            borderTop: true,
          },
        },
      ],
    },
  ],
}
